var enc=encodeURIComponent,makeClickUrl=function(c,b,h,l){b=b?'?'+b:'';var n=!1,m=!1;if(0<h.length){var n=!0,v=h.indexOf('%2F%2F');0<v&&9>v&&(h=decodeURIComponent(h));h=-1==h.indexOf('://')?'http://'+h:h;2048>=h.length+enc(c+b).length?(c=h+enc(c+b),m=!0):c=h+enc(c)}else 2048>=b.length+c.length&&(c+=b,m=!0);return l?{url:c,isEncoded:n,withParams:m}:c},onUnload=function(c){try{var b=!1,h=function(){b||(b=!0,c())},l=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;l&&window.addEventListener('pagehide',
h,!1);var n=window.onbeforeunload;window.onbeforeunload=function(b){h();if(n)return n(b)}}catch(m){}};function callAjax(c){var b=new XMLHttpRequest;b.open('GET',c,!1);try{b.send()}catch(h){}}function trancateUrl(c){c+='';var b=400;return c.length>b?c.substr(0,b):c}
function url(){var c='',b='',h='',l=window;try{c=top.document.location}catch(n){try{b=document.location;if(b==top.location)c=b;else for(var m=0;1E3>m;){c=l.document.location;l.document.referrer&&(h=l.document.referrer);if(l==l.parent)break;else l.document.referrer&&(c=h);l=l.parent;m++}if(''==c||null==c)c=h?h:b}catch(v){h&&''!=h?c=h:''==c&&(c=b)}}return c=trancateUrl(c)}
(function(){function c(a){for(var f='',d=a.length,k=0;k<d;++k)f+=a[k]?'1':'0';return 0<f.length?parseInt(f,2):''}function b(a){try{return a()}catch(f){}return!1}function h(){var a=[];a[0]=b(function(){return typeof IntersectionObserver===A});a[1]=b(function(){return!!(navigator.plugins&&0==navigator.plugins.length)});a[2]=b(function(){return void 0!==document.body.style.zoom});a[3]=b(function(){return!(!navigator.mimeTypes||!(void 0!=navigator.mimeTypes[B]&&navigator.mimeTypes[B].enabledPlugin))});
a[4]=b(function(){return Modernizr.webgl});a[5]=b(function(){return Modernizr.webglextensions});a[6]=b(function(){return''!=Modernizr.video.ogg});a[7]=b(function(){return''!=Modernizr.video.h264});a[8]=b(function(){return''!=Modernizr.video.webm});a[9]=b(function(){return Modernizr.audio});a[10]=b(function(){var a;a:{if(window.WebGLRenderingContext){var d=document.createElement('canvas'),k=['webgl2','experimental-webgl2'],b=!1,c;for(c in k)try{if((b=d.getContext(k[c]))&&typeof b.getParameter==A){a=
!0;break a}}catch(g){}}a=!1}return a});a[11]=b(function(){var a;a=document.createElement('AUDIO');return a=!(!a||!a.audioTracks)});a[12]=b(function(){return void 0!=window.mozPaintCount});a[13]=b(function(){return'undefined'!==typeof InstallTrigger});a[14]=b(function(){return!!document.documentMode});a[15]=b(function(){return!!window.chrome&&!!window.chrome.webstore});a[16]=b(function(){return!!window.StyleMedia});return a}function l(){try{var a=window,f=a.$sf,d=f&&f.ext;if(f&&d){f='';d.meta&&(f+=
'sf_v\x3d'+d.meta('sf_ver')+';cookies\x3d'+d.meta('ck_on'));if(d.geom)var k=d.geom(),f=f+(';geom\x3d'+JSON.stringify(k,y));if(d.supports)var b=d.supports(),f=f+(';supports\x3d'+JSON.stringify(b,y));d.inViewPercentage&&(f+=';ivp\x3d'+y(null,d.inViewPercentage()));d.winHasFocus&&(f+=';vhf\x3d'+d.winHasFocus());return f+=';domain\x3d'+trancateUrl(a.document.referrer)}}catch(c){return'error: '+c}return''}function n(a){document.body.appendChild(a)}function m(a,f,d,k){var b=[],c;d&&(c=document.createElement(a));
for(var g in f)d?(c[g]=f[g],k&&(c.innerHTML=k)):b.push(g+"\x3d'"+f[g]+"'");k||(k='');return d?c:'\x3c'+a+' '+b.join(' ')+'\x3e'+k+'\x3c/'+a+'\x3e'}function v(a,f){var d=new XMLHttpRequest;d.open('GET',a,!1);d.withCredentials=!0;try{d.send(null),200!==d.status&&f()}catch(k){f()}d.onerror=function(){f()}}function g(a,f,d){void 0===d&&(d='');return a[f]?a[f]:d}function C(a){try{for(var f=[],d=0;d<a.length;d++){var k=a[d],b=k.price,c=k.quantity;void 0===b||void 0===c?f.push(k.id):f.push(k.id+':'+b+':'+
c)}return f.join('|')}catch(g){return''}}function D(){return'undefined'!==typeof __GetI_context&&'app'==__GetI_context}function E(){try{if(window.top==window)return r.NO_IFRAME;for(var a=window,f=0;a.parent!=a&&1E3>f;){f++;if(a.parent.document.domain!=a.document.domain)return r.XD_IFRAME;a=a.parent}return r.IFRAME}catch(d){}return r.XD_IFRAME}function t(a,f){var d='scr\x3d'+screen.width+'x'+screen.height+'x'+screen.colorDepth+'\x26uit\x3d'+Math.floor(Date.now())+'\x26ifr\x3d'+E()+'\x26tz\x3d'+(new Date).getTimezoneOffset();
f&&a&&(a.bl&&(d+='\x26bl\x3d'+a.bl),a.s&&(d+='\x26s\x3d'+a.s));if(!D()){var b='\x26url\x3d'+enc(url())+'\x26rf\x3d',c=enc,g;try{g=trancateUrl(top.document.referrer)}catch(h){g=''}g=b+c(g)+'\x26pl\x3d';for(var b=[],c=navigator.plugins,p=0;p<c.length;p++)b.push(c[p].name),b.push(','),b.push(c[p].filename),b.push(','),b.push(c[p].description),b.push(','),b.push(c[p].version),b.push(';');b=b.join('');for(i=c=0;i<b.length;i++)p=b.charCodeAt(i),c=p+(c<<6)+(c<<16)-c;d+=g+c}return d}function F(a){return(a=
document.cookie.match(RegExp('(?:^|; )'+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+'\x3d([^;]*)')))?decodeURIComponent(a[1]):null}function G(a){var f,d='undefined'==typeof __GetI_domain?'px.adhigh.net':__GetI_domain,b='undefined'==typeof __GetI_static_domain?d:__GetI_static_domain,m=function(a){var b=a.type;switch(b){case 'VIEW':f=a;var k='site_id\x3d'+g(a,'site_id')+'\x26trk\x3d'+g(a,'site_tracking')+'\x26product_id\x3d'+enc(g(a,'product_id'))+'\x26product_price\x3d'+g(a,'product_price')+'\x26category_id\x3d'+
enc(g(a,'category_id'))+'\x26user_data\x3d'+serializeUserData(g(a,'user_data'))+'\x26pixel_id\x3d'+enc(g(a,'pixel_id'));asyncPix(d,'/p/tracking',k+'\x26'+t(a,!0));var b=1E3*g(a,'repeat_pixel_time_s',30),m=g(a,'repeat_count',1);if(0<m)var s=0,n=setInterval(function(){s<m?(s++,(new Image).src=gifPixUrl(d,'/p/tracking',k+'\x26rptd\x3d1\x26'+t(a,!0)+'\x26syncs\x3ddefault')):clearInterval(n)},b);break;case 'CONVERSION':f=a;asyncPix(d,'/p/conversion','site_id\x3d'+g(a,'site_id')+'\x26trk\x3d'+g(a,'site_tracking')+
'\x26conversion_id\x3d'+enc(g(a,'conversion_id'))+'\x26transaction_id\x3d'+enc(g(a,'transaction_id'))+'\x26revenue\x3d'+g(a,'revenue')+'\x26attributed\x3d'+g(a,'attributed','false')+'\x26pixel_id\x3d'+enc(g(a,'pixel_id'))+'\x26order\x3d'+enc(C(g(a,'order',[])))+'\x26'+t(a,!0));break;case 'CART_ADD':f=a;asyncPix(d,'/p/cart','site_id\x3d'+g(a,'site_id')+'\x26trk\x3d'+g(a,'site_tracking')+'\x26product_id\x3d'+enc(g(a,'product_id',''))+'\x26product_price\x3d'+g(a,'product_price','')+'\x26order\x3d'+enc(C(g(a,
'order',[])))+'\x26'+t(a,!0));break;case 'IMP':'true'===g(a,'deliveredAdmTracking','false')&&((new Image).src=getProtocolPrefix()+d+'/p/d_imp.gif?from_tag\x3dp_script_img\x26b\x3d'+a.bidResponse);var x=a.evId,b=t(a,!1),q='id\x3d'+x+'\x26s\x3d'+a.ssp+'\x26w\x3d'+enc(a.winPrice)+'\x26b\x3d'+enc(a.bidResponse)+'\x26f\x3d'+c(h())+'\x26';'true'==g(a,'detectSafeFrame','false')&&(q+='sfs\x3d'+enc(l())+'\x26');0<a.clPref.length&&(q+='cl\x3d'+enc(a.clPref)+'\x26');'companionId'in a&&0<a.companionId.length&&
(q+='companion\x3d'+enc(a.companionId)+'\x26');var r=q+b,w='true'===g(a,'async','true');if(D())if(q=function(){pix(d,'/p/imp',r,w)},'true'==g(a,'inAppImpCallAjax','false'))v(pixUrl(d,'/p/imp',r),q);else{var u;'true'==g(a,'retryInAppImpCall','false')&&(u='__GetI_load_imp_'+x,window[u]=q);pix(d,'/p/imp',r,w,null,null,u)}else pix(d,'/p/imp',r,w);u='__GetI_callback_'+x;if(window[u])window[u](b,a);'true'==a.vt&&(__GetI_vt.push(a),setTimeout(__GetI_track_view,0));a.tpa&&a.tpa()}};a.push=m;for(var s=a.pop();s;s=
a.pop())s&&m(s);if(f&&(-1!==url().indexOf('giclickid')||null!=F('giclickid'))){onUnload(function(){callAjax(pixUrl(d,'/p/engage','time_on_page\x3d'+Math.round(((new Date).getTime()-H)/1E3)+'\x26site_id\x3d'+g(f,'site_id')+'\x26product_id\x3d'+enc(g(f,'product_id',''))+'\x26product_price\x3d'+g(f,'product_price','')+'\x26'+t(f,!1)))});var n=!1;asyncPix(b,'/vf','',function(){var a=!1,b=function(){'undefined'!=typeof ifvisible&&!a&&(a=!0,ifvisible.on('wakeup',function(){n||(n=!0,asyncPix(d,'/p/engage',
'was_active\x3dtrue\x26site_id\x3d'+g(f,'site_id')+'\x26product_id\x3d'+enc(g(f,'product_id',''))+'\x26product_price\x3d'+g(f,'product_price','')+'\x26'+t(f,!1)))}),ifvisible.idle())};b();setInterval(b,1E3)})}}var I='text/javascript',z='script',A='function',B='application/x-shockwave-flash',H=(new Date).getTime(),y=function(a,b){return b&&b.toFixed?Number(b.toFixed(2)):b};getProtocolPrefix=function(){var a='undefined'==typeof __GetI_protocol?'':__GetI_protocol;return a='http'===a&&'https:'!==document.location.protocol?
'http://':'https://'};pixUrl=function(a,b,d){return makePixUrl(a,b+'.js',d)};makePixUrl=function(a,b,d){a=getProtocolPrefix()+a;return a+(b+'?'+d)};gifPixUrl=function(a,b,d){return makePixUrl(a,b+'.gif',d)};pix=function(a,b,d,c,g,h,l){a=pixUrl(a,b,d);a={type:I,src:a};h&&(a.id=h);if(c){h=m(z,a,!0);h.async=c;c=document.getElementsByTagName(z)[0];if(g){var p=!1;l&&h.addEventListener('error',window[l]);h.addEventListener('load',function(a){p||(p=!0,g(null,a))},!1);h.onreadystatechange=function(){if(('complete'==
this.readyState||'loaded'==this.readyState)&&!p)p=!0,g(null,e)}}c.parentNode.insertBefore(h,c)}else l&&(a.onerror='window["'+l+'"]()'),n(m(z,a,!0))};asyncPix=function(a,b,d,c){pix(a,b,d,!0,c)};serializeUserData=function(a){if(a&&Object.keys){for(var b=Object.keys(a),d='',c=0;c<b.length;c++)0<c&&(d+='|'),d+=b[c]+':'+a[b[c]];return d}return''};var r={NO_IFRAME:0,IFRAME:1,UNKNOWN:2,XD_IFRAME:3};if('undefined'==typeof __GetI||null==__GetI)__GetI=[];G(__GetI)})();